name: Build and Deploy to Azure Container App

on:
  push:
    tags:
      - 'v*'  # Triggert das Build automatisch bei Tags wie v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Tag Version
        id: tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/my-agenda-app:latest
            ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/my-agenda-app:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Stellt sicher, dass das Build-Job abgeschlossen ist

    steps:
      - name: Extract Azure Credentials
        run: |
          echo "AZURE_CLIENT_ID=$(jq -r .clientId <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "AZURE_CLIENT_SECRET=$(jq -r .clientSecret <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "AZURE_SUBSCRIPTION_ID=$(jq -r .subscriptionId <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=$(jq -r .tenantId <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update 
            --name my-agenda-app
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
            --image ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/my-agenda-app:${{ env.VERSION }}
            --registry-server ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
            --registry-username ${{ secrets.AZURE_ACR_USERNAME }}
            --registry-password ${{ secrets.AZURE_ACR_PASSWORD }}
