name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-agenda-app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: |
          cd my-agenda-app
          npm run lint
        working-directory: ./my-agenda-app  # Specify the correct directory

      - name: Run Type Check
        run: |
          cd my-agenda-app
          npm run check
        working-directory: ./my-agenda-app  # Specify the correct directory

      - name: Build Project
        run: |
          cd my-agenda-app
          npm run build
        working-directory: ./my-agenda-app  # Specify the correct directory

      - name: Run Playwright Tests
        run: |
          cd my-agenda-app
          npm run test:e2e
        env:
          CI: true
        working-directory: ./my-agenda-app  # Specify the correct directory

      - name: Check for Test Results Directory
        run: |
          if [ ! -d "my-agenda-app/test-results" ]; then
            echo "Test results directory not found"
            exit 1
          fi
        working-directory: ./my-agenda-app  # Specify the correct directory

      - name: Upload Playwright Test Artifacts (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ./my-agenda-app/test-results/